FROM continuumio/miniconda3:25.1.1-2

# Install metamate directly into base environment

RUN conda install -y -c bioconda -c conda-forge \
    metamate=0.4.3 \
    seqkit=2.13.0 && \
    conda clean --all --yes

# Create default specifications file
RUN mkdir -p /default_specs && \
    echo "[library; n; 0-1/2]" > /default_specs/specifications0.txt

