ARG NEXTITS_VERSION=1.1.0
ARG NEXTFLOW_VERSION=25.10.4

FROM vmikk/nextits:${NEXTITS_VERSION} AS main

## Re-declare build args inside this stage so RUN can use them
ARG NEXTITS_VERSION
ARG NEXTFLOW_VERSION

ENV NEXTITS_DIR=/opt/pipelines/NextITS
ENV NXF_HOME=/opt/software/conda/bin
# ENV PATH="${NXF_HOME}:${PATH}"

USER root

RUN set -eux; \
    mkdir -p "${NXF_HOME}" "${NEXTITS_DIR}"; \
    ## Install Nextflow into $NXF_HOME
    NXF_VER="${NEXTFLOW_VERSION}" curl -s https://get.nextflow.io | bash ; \
    mv nextflow "${NXF_HOME}/nextflow"; \
    chmod 0755 "${NXF_HOME}/nextflow"; \
    ## Pull NextITS into $NEXTITS_DIR
    git clone --depth 1 --branch "${NEXTITS_VERSION}" https://github.com/vmikk/NextITS "${NEXTITS_DIR}" ; \
    rm -rf "${NEXTITS_DIR}/.git" ; \
    ## Ensure the runtime user can access everything
    chown -R nextits:nextits "${NXF_HOME}" "${NEXTITS_DIR}"

USER nextits

