FROM ubuntu:22.04


# Install base utilities
RUN apt-get update && \
    apt-get install -y build-essential  && \
    apt-get install -y wget && \
    apt-get install -y pigz && \
    apt-get install -y gzip && \
    apt-get install -y libdw1 && \
    apt-get install -y libuv1 && \
    apt-get install libnghttp2-14 && \
    apt-get clean && \
    wget ftp://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/ORFfinder/linux-i64/ORFfinder.gz && \
    rm -rf /var/lib/apt/lists/*


# Install ORFfinder and seqkit
RUN gunzip ORFfinder.gz
RUN chmod 755 ORFfinder
RUN mv ORFfinder /bin/.
RUN wget https://github.com/shenwei356/seqkit/releases/download/v2.3.0/seqkit_linux_amd64.tar.gz -O /tmp/seqkit.tar.gz && \
    tar zxvf /tmp/seqkit.tar.gz -C /usr/bin/ && rm /tmp/seqkit.tar.gz

# Install perl
RUN apt-get install perl

