FROM ubuntu:22.04
RUN apt-get update -y  \
    && apt-get install wget -y \
    && apt-get install gawk -y \
    && apt-get install libc6 -y \
    && apt-get install python3 -y \
    && apt-get install python3-pip -y \
    && python3 -m pip install biopython \
    && python3 -m pip install psutil==7.0.0 \
    && wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.16.0/ncbi-blast-2.16.0+-x64-linux.tar.gz -O /tmp/blast.tar.gz \
    && tar zxvf /tmp/blast.tar.gz -C /usr/bin \
    && wget https://github.com/shenwei356/seqkit/releases/download/v2.13.0/seqkit_linux_amd64.tar.gz -O /tmp/seqkit.tar.gz \
    && tar zxvf /tmp/seqkit.tar.gz -C /usr/bin
ENV PATH=/usr/bin/ncbi-blast-2.16.0+/bin:$PATH