FROM ubuntu:22.04
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        wget \
        unzip \
        pigz \
        build-essential \
        zlib1g-dev \
        libtre-dev \
    && wget https://github.com/shenwei356/seqkit/releases/download/v2.13.0/seqkit_linux_amd64.tar.gz -O /tmp/seqkit.tar.gz \
    && tar zxvf /tmp/seqkit.tar.gz -C /usr/bin/ \
    && rm /tmp/seqkit.tar.gz \
    && wget https://github.com/indraniel/fqgrep/archive/v0.4.4.zip \
    && unzip v0.4.4.zip \
    && rm v0.4.4.zip \
    && cd fqgrep-0.4.4 \
    && make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV PATH="$PATH:/fqgrep-0.4.4"