FROM ubuntu:24.04
# ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y \
    && apt-get install bc -y \ 
    && apt-get install build-essential -y \
    && apt-get install python3-dev -y \
    && apt-get update -y \
    && apt-get install python3-pip -y \
    && python3 -m pip install --break-system-packages biopython \
    && apt-get install curl -y \
    && apt-get install pigz -y \
    && apt-get install wget -y \
    && wget https://github.com/shenwei356/seqkit/releases/download/v2.13.0/seqkit_linux_amd64.tar.gz -O /tmp/seqkit.tar.gz \
    && tar zxvf /tmp/seqkit.tar.gz -C /usr/bin/ \
    && rm /tmp/seqkit.tar.gz \
    && python3 -m pip install --break-system-packages cutadapt==5.2 \
    && apt-get remove wget -y curl -y
#ADD src/pipecraft-core/service_scripts/submodules /bin/submodules