FROM continuumio/miniconda3:4.12.0
# ARG DEBIAN_FRONTEND=noninteractive
RUN conda init bash
RUN apt-get update
RUN apt-get install --no-install-recommends r-base -y
RUN Rscript -e 'install.packages("reshape2", repos="https://cloud.r-project.org")'
RUN apt-get install wget -y
RUN apt-get install unzip -y
RUN apt-get install pigz -y
RUN apt-get install libuv1 -y
RUN apt-get install libdw1 -y
RUN apt-get install gzip -y
RUN wget https://github.com/terrimporter/MetaWorks/releases/download/v1.11.1/MetaWorks1.11.1.zip
RUN unzip MetaWorks1.11.1.zip
RUN rm MetaWorks1.11.1.zip
RUN cd MetaWorks1.11.1 && conda env create -f environment.yml
RUN . /root/.bashrc && \
    conda init bash && \
    cd MetaWorks1.11.1 && \
    conda activate MetaWorks_v1.11.1
RUN wget ftp://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/ORFfinder/linux-i64/ORFfinder.gz
RUN gunzip ORFfinder.gz
RUN mv ORFfinder /bin/.
