FROM alpine:3.14

ARG USERNAME=pipecraft
ARG USER_UID=1000
ARG USER_GID=$USER_UID


RUN apk add build-base \
    && apk add automake \
    && apk add parallel \
    && apk add --no-cache --upgrade grep \
    && apk add autoconf  \
    && apk add pigz  \
    && apk add bash  \
    && apk add wget  \
    && apk add git  \
    && apk add zlib-dev \
    && apk add bzip2-dev \
    && wget https://github.com/shenwei356/seqkit/releases/download/v2.0.0/seqkit_linux_amd64.tar.gz -O /tmp/seqkit.tar.gz  \
    && tar zxvf /tmp/seqkit.tar.gz -C /usr/bin/ && rm /tmp/seqkit.tar.gz \
    && git clone --branch v2.18.0 https://github.com/torognes/vsearch.git \
    && cd vsearch && ./autogen.sh && ./configure && make && make install
RUN apk del git && apk del wget
RUN usermod -u 1000 www-data
