FROM ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    default-jre-headless \
    bash \
    wget \
    unzip \
    pigz \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && wget https://github.com/usadellab/Trimmomatic/releases/download/v0.40/Trimmomatic-0.40.zip \
    && unzip Trimmomatic-0.40.zip \
    && mv trimmomatic-0.40.jar /trimmomatic.jar \
	&& wget https://github.com/shenwei356/seqkit/releases/download/v2.13.0/seqkit_linux_amd64.tar.gz -O /tmp/seqkit.tar.gz && \
	tar zxvf /tmp/seqkit.tar.gz -C /usr/bin/ && rm /tmp/seqkit.tar.gz

