FROM ubuntu:18.04
# This dockerfile is based on https://hub.docker.com/r/tbattaglia/kraken2/dockerfile
RUN apt-get update && apt-get -y install \
  wget \
  zlib1g-dev \
  make \
  python \
  perl \
  g++ \
  ca-certificates \
  nfs-common \
  python-biopython

RUN wget https://github.com/DerrickWood/kraken2/archive/v2.1.1.tar.gz && \
  tar -xzf v2.1.1.tar.gz && \
  rm -rf v2.1.1.tar.gz && \
  cd kraken2-2.1.1 && \
  ./install_kraken2.sh .

ENV PATH="$PATH:/kraken2-2.1.1" \
    LC_ALL=C

RUN wget https://github.com/jenniferlu717/Bracken/archive/v2.6.0.tar.gz && \
  tar -xzf v2.6.0.tar.gz && \
  rm -rf v2.6.0.tar.gz && \
  mv Bracken-2.6.0 bracken && \
  cd /bracken && \
  sh ./install_bracken.sh . && \
  ln -s /bracken/bracken /usr/local/bin/bracken && \
  ln -s /bracken/src/est_abundance.py /usr/local/bin/est_abundance.py && \
  ln -s /bracken/src/kreport2mpa.py /usr/local/bin/kreport2mpa.py && \
  ln -s /bracken/bracken-build /usr/local/bin/bracken-build