FROM quay.io/qiime2/core:2022.2

RUN conda config --add channels defaults \
  && conda config --add channels bioconda \
  && conda config --add channels conda-forge \
  && conda config --set channel_priority flexible \
  && conda install -y -n base -c conda-forge deicode=0.2.4 \
  && R -e "install.packages('optparse', dependencies=TRUE, repos='http://cran.rstudio.com/')" \
  && conda clean --all --yes

COPY src/pipecraft-core/service_scripts/rpca.py /usr/local/lib/python3.8/site-packages/deicode/rpca.py
COPY src/pipecraft-core/service_scripts/_standalone_rpca.py /usr/local/lib/python3.8/site-packages/deicode/scripts/_standalone_rpca.py
