version: "3.4"

services:
  vsearch-quality:
    image: pipecraft/vsearch:2.15.0
    volumes:
      - ./service_scripts:/service_scripts
      - ${userDirectory}:/input
      - ${userDatabases}:/user_databases
      - ./installed_databases:/installed_databases
    env_file:
      - ./env_files/vsearch-quality.env
    working_dir: ${workingDir}
    entrypoint: /service_scripts/vsearch-quality.sh
  mmseqs2-classifier:
    image: pipecraft/mmseqs2:12
    volumes:
      - ./service_scripts:/service_scripts
      - ${userDirectory}:/input
      - ${userDatabases}:/user_databases
      - ./installed_databases:/installed_databases
    env_file:
      - ./env_files/mmseqs2-classifier.env
    working_dir: ${workingDir}
    entrypoint: /service_scripts/mmseqs2-classifier.sh
  naive-bayes-classifier:
    image: pipecraft/qiime2:2020.8.0
    volumes:
      - ./service_scripts:/service_scripts
      - ${userDirectory}:/input
      - ${userDatabases}:/user_databases
      - ./installed_databases:/installed_databases
    env_file:
      - ./env_files/naive-bayes-classifier.env
    working_dir: ${workingDir}
    entrypoint: /service_scripts/naive-bayes-classifier.sh
  dada2-classifier:
    image: pipecraft/dada2:3.10
    volumes:
      - ./service_scripts:/service_scripts
      - ${userDirectory}:/input
      - ${userDatabases}:/user_databases
      - ./installed_databases:/installed_databases
    env_file:
      - ./env_files/dada2-classifier.env
    working_dir: ${workingDir}
    entrypoint: /service_scripts/dada2-classifier.sh
  kraken2-classifier:
    image: pipecraft/krakern2:2.1.1
    volumes:
      - ./service_scripts:/service_scripts
      - ${userDirectory}:/input
      - ${userDatabases}:/user_databases
      - ./installed_databases:/installed_databases
    env_file:
      - ./env_files/kraken2-classifier.env
    working_dir: ${workingDir}
    entrypoint: /service_scripts/kraken2-classifier.sh
