FROM alpine:3.10

RUN apk add build-base && apk add R && apk add R-dev && apk add linux-headers && apk add libjpeg-turbo-dev
ADD ImageDevelopment/dada2_install.R /
RUN Rscript dada2_install.R

# dada2_install.R contents:
# install.packages("Rcpp" ,repos = "http://cran.us.r-project.org")
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager" ,repos = "http://cran.us.r-project.org")
# BiocManager::install("dada2", version = "3.10")

RUN apk del R-dev && apk del build-base
